[2024-02-13T01:06:17.118+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v2.second_task manual__2024-02-13T01:06:15.044462+00:00 [queued]>
[2024-02-13T01:06:17.127+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v2.second_task manual__2024-02-13T01:06:15.044462+00:00 [queued]>
[2024-02-13T01:06:17.127+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-02-13T01:06:17.141+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): second_task> on 2024-02-13 01:06:15.044462+00:00
[2024-02-13T01:06:17.147+0000] {standard_task_runner.py:60} INFO - Started process 444 to run task
[2024-02-13T01:06:17.150+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v2', 'second_task', 'manual__2024-02-13T01:06:15.044462+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpea17_n9r']
[2024-02-13T01:06:17.151+0000] {standard_task_runner.py:88} INFO - Job 8: Subtask second_task
[2024-02-13T01:06:17.191+0000] {task_command.py:423} INFO - Running <TaskInstance: our_first_dag_v2.second_task manual__2024-02-13T01:06:15.044462+00:00 [running]> on host e97f82a89325
[2024-02-13T01:06:17.292+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='shiv' AIRFLOW_CTX_DAG_ID='our_first_dag_v2' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-13T01:06:15.044462+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-13T01:06:15.044462+00:00'
[2024-02-13T01:06:17.293+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-02-13T01:06:17.294+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo I am the second one here!']
[2024-02-13T01:06:17.314+0000] {subprocess.py:86} INFO - Output:
[2024-02-13T01:06:17.317+0000] {subprocess.py:93} INFO - I am the second one here!
[2024-02-13T01:06:17.318+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-02-13T01:06:17.354+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v2, task_id=second_task, execution_date=20240213T010615, start_date=20240213T010617, end_date=20240213T010617
[2024-02-13T01:06:17.404+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-13T01:06:17.419+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
